version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: todo-db
    ports:
      - 5431:5431
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  redis:
    container_name: redis-todo
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
