server:
  port: 8080

spring:
  application:
    name: SpringToDo

  datasource:
    url: jdbc:postgresql://localhost:5431/task
    username: admin
    password: admin

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true